using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace Infrastructure.Models;

[Table("accounts")]
public class Account : BaseModel
{
    [PrimaryKey("id", false)] // autogenerated in DB
    public Guid Id { get; set; }

    [Column("user_id")]
    public Guid UserId { get; set; }

    [Column("name")]
    public string Name { get; set; } = "";

    [Column("currency")]
    public string Currency { get; set; } = "EUR";

    [Column("sort_order")]
    public int SortOrder { get; set; }

    [Column("show_balance")]
    public bool ShowBalance { get; set; } = true;

    // Enum key (AccountIcon), e.g. "Wallet", "Card"
    [Column("icon_key")]
    public string IconKey { get; set; } = "Wallet";

    // Actual balance (planned transactions are NOT included)
    [Column("balance_actual")]
    public decimal BalanceActual { get; set; }

    // Expected balance (planned transactions ARE included)
    [Column("balance_expected")]
    public decimal BalanceExpected { get; set; }

    [Column("is_archived")]
    public bool IsArchived { get; set; }

    [Column("created_at")]
    public DateTimeOffset CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTimeOffset UpdatedAt { get; set; }
}
