using Domain.Enums;
using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace Infrastructure.Models
{
    [Table("transactions")]
    public class Transaction : BaseModel
    {
        [PrimaryKey("id", false)] // autogenerated in DB
        public Guid Id { get; set; }

        [Column("user_id")]
        public Guid UserId { get; set; } // DB sets default auth.uid()

        [Column("account_id")]
        public Guid AccountId { get; set; }

        [Column("occurred_on")]
        public DateOnly OccurredOn { get; set; } // DB type: date

        [Column("amount")]
        public decimal Amount { get; set; } // DB type: numeric(12,2)

        [Column("entry_type")]
        public EntryType EntryType { get; set; }// DB type: int2 (0=income, 1=expense)

        [Column("is_planned")]
        public bool IsPlanned { get; set; }

        [Column("currency")]
        public string Currency { get; set; } = "EUR"; // DB default 'EUR'

        [Column("category_id")]
        public Guid CategoryId { get; set; }

        [Column("note")]
        public string? Note { get; set; }

        [Column("created_at")]
        public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; // DB default now()
    }
}
